jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - run: |
          npm ci
          composer install --no-dev
      - uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          exclude: |
            **/.git*
            **/.git*/**
            **/tests/**
            .env
            composer.*
            package-lock.json
            package.json
            phpunit.*
          log-level: minimal
          password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          server: ${{ secrets.ftp_server }}
          server-dir: ${{ secrets.ftp_server_dir }}
          username: ${{ secrets.ftp_username }}

on:
  push:
    branches: ['main']

permissions:
  contents: read
